INSERT INTO DISCO (FECHA_EDICION, TITULO_DISCO, GENERO_DISCO, ES_FISICO, ES_DIGITAL, TAMAÑO_DISCO)
VALUES ('2018-01-04', 'PAINT IT BLACK', 'ROCK', TRUE, TRUE, 5);


INSERT INTO CANCION (DURACION, NOMBRE_CANCION)
VALUES (2.30, 'PAINT IT BLACK');

INSERT INTO CANCION_DISCO(ID_CANCION, ID_DISCO)
(
	WITH
	t1 as (SELECT CANCION.ID_CANCION FROM CANCION WHERE NOMBRE_CANCION = 'PAINT IT BLACK'),
	t2 as (SELECT DISCO.ID_DISCO FROM DISCO WHERE TITULO_DISCO = 'PAINT IT BLACK')
	select * from t1 cross join t2
);

INSERT INTO COMPOSITOR_CANCION(ID_CANCION, ID_COMPOSITOR)
(
	WITH
	t1 as (SELECT CANCION.ID_CANCION FROM CANCION WHERE NOMBRE_CANCION = 'PAINT IT BLACK'),
	t2 as (SELECT COMPOSITOR.ID_COMPOSITOR FROM COMPOSITOR WHERE ID_COMPOSITOR 
		   IN (SELECT ID_COMPOSITOR FROM COMPOSITOR WHERE DNI_MUSICO IN 
			   (SELECT DNI_MUSICO FROM MUSICO WHERE DNI_MUSICO = '25801802B')
			  )
		  )
	select * from t1 cross join t2
);

INSERT INTO DISCO_GRUPO(ID_DISCO, ID_GRUPO)
(
	WITH
	t1 as (SELECT DISCO.ID_DISCO FROM DISCO WHERE TITULO_DISCO = 'PAINT IT BLACK'),
	t2 as (SELECT GRUPO.ID_GRUPO FROM GRUPO WHERE NOMBRE_GRUPO = 'THE ROLLIN'' STONES')
	select * from t1 cross join t2
);

SELECT * FROM CANCION;

