/*
select grupo.nombre_grupo from grupo where genero_grupo = 'Jazz';
SELECT DISTINCT * FROM MUSICO INNER JOIN INSTRUMENTO_MUSICO ON INSTRUMENTO_MUSICO.DNI_MUSICO = MUSICO.DNI_MUSICO INNER JOIN INSTRUMENTO ON INSTRUMENTO_MUSICO.ID_INSTRUMENTO = INSTRUMENTO.ID_INSTRUMENTO WHERE INSTRUMENTO.TIPO_INSTRUMENTO = 'Bateria'


*/

