
/* TRIGGER PARA CALCULO DE PUNTOS */

CREATE OR REPLACE FUNCTION FN_PUNTOS_GANADOS() RETURNS TRIGGER AS $FN_PUNTOS_GANADOS$
    BEGIN 
    UPDATE COMPRA
	SET COMPRA.PUNTOS_GANADOS = new.compra.precio * 0.1
	FROM 
	WHERE new.compra.id_compra = compra.id_compra;
    RETURN NULL;
    END;

$FN_PUNTOS_GANADOS$ LANGUAGE PLPGSQL;


CREATE TRIGGER TG_PUNTOS_GANADOS BEFORE INSERT OR UPDATE ON COMPRA
FOR EACH ROW 

EXECUTE PROCEDURE FN_PUNTOS_GANADOS();

CREATE OR REPLACE FUNCTION FN_PUNTOS_GASTADOS() RETURNS TRIGGER AS $FN_PUNTOS_GASTADOS$
   
    BEGIN 
    UPDATE COMPRA 
	SET compra.precio = compra.precio - compra.puntos_gastados * 0.05 * compra.precio; 
    RETURN NULL;
    END;

$FN_PUNTOS_GASTADOS$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_PUNTOS_GASTADOS BEFORE INSERT OR UPDATE ON COMPRA 
FOR EACH ROW 

EXECUTE PROCEDURE FN_PUNTOS_GASTADOS();




